### ISSUE TITLE
Upgrade to minikube 1.18.0

### ISSUE THREAD

**Issue by apupier** [lilic/travis-minikube#24]
it is unfortunately not just a matter of updating version. it seems that conntrack needs to be provided too:

```
X Sorry, Kubernetes v1.18.0 requires conntrack to be installed in root's path
The command "sudo minikube start --vm-driver=none --kubernetes-version=v1.18.0" failed and exited with 78 during .
```

conntrack installation steps here http://conntrack-tools.netfilter.org/manual.html#Installation
(I have not tried yet)

**Comment by disposab1e** [comment]
@apupier 
```
sudo apt-get update 
sudo apt-get install -y conntrack
```
will do the job on travis-ci / dist: bionic

**Comment by lilic** [comment]
Thanks for the issue, indeed there are some changes, will update the example.

**Comment by lilic** [comment]
Closed by https://github.com/lilic/travis-minikube/pull/25 🎉
