### ISSUE TITLE
panic: no-vm not supported

### ISSUE THREAD

**Issue by riuvshin** [LiliC/travis-minikube#4]
tried to do this on my localhost but it fails 
```
Starting local Kubernetes v1.8.0 cluster...
Starting VM...
panic: no-vm not supported

goroutine 1 [running]:
```
any idea how to fix that? 
thanks in advance!

**Comment by LiliC** [comment]
@riuvshin Most likely your OS is not Linux. Setting up minikube with no VM only works on Linux. 

What were you trying to do?

**Comment by riuvshin** [comment]
I'm using OS X

**Comment by LiliC** [comment]
@riuvshin Should work fine on Linux. On OS X you can just skip the `no-vm` flag and it should work. The flag is there so things work for running the k8s cluster on TravisCI.

**Comment by LiliC** [comment]
BTW @riuvshin Closed this issue, but if you are experiencing any problems with a TravisCI setup when running this, feel free to open a new issue! 👍 🙂

**Comment by riuvshin** [comment]
without `no-vm` it probably will use VBox while I;m looking for no VM set-up.
anyways thanks a lot and have a nice day :)

**Comment by LiliC** [comment]
@riuvshin Yes, it will use a VM. Not aware of a non-VM setup on an OSX.

You are welcome! :)
