### ISSUE TITLE
Thanks for the code/snippet!

### ISSUE THREAD

**Issue by cdancy** [LiliC/travis-minikube#6]
Banged my head trying to get travis wired up for kubernetes to work with our new [gradle-kubernetes-plugin](https://github.com/bmuschko/gradle-kubernetes-plugin). I don't even want to say, or post, what I was doing but the config I had setup was ridiculous and this is infinitely simpler. In either event ... thanks again!

**Comment by LiliC** [comment]
@cdancy You are welcome, glad it was helpful! 🙂
